version: '3.4'

services:
  db:
    restart: always
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis

  django:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - DJANGO_SECRET_KEY=seekret
    command: ./wait-for-it.sh db:5432 -- ./spacenews/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media:/app/media
    depends_on:
      - db

  nuxt:
    build:
      context: ./frontend
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
      - media:/app/media
    ports:
      - "3000:3000"
    depends_on:
      - django
      - redis

volumes:
  pgdata:
  media:
